-- Migración 001: columnas de auditoría en tablas de parámetros globales
-- Ejecutar como usuario ESTIMADOR contra FREEPDB1

ALTER TABLE PARAMETROS_COMPLEJIDAD
    ADD (UPDATED_BY VARCHAR2(255), UPDATED_AT TIMESTAMP);

ALTER TABLE PARAMETROS_TIEMPO_ADICIONAL
    ADD (UPDATED_BY VARCHAR2(255), UPDATED_AT TIMESTAMP);

ALTER TABLE PARAMETROS_ETAPA_CASE
    ADD (UPDATED_BY VARCHAR2(255), UPDATED_AT TIMESTAMP);

CREATE OR REPLACE TRIGGER TRG_PARAM_COMPLEJIDAD_BU
BEFORE UPDATE ON PARAMETROS_COMPLEJIDAD
FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY := SYS_CONTEXT('APEX$SESSION','APP_USER');
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PARAM_TIEMPO_ADIC_BU
BEFORE UPDATE ON PARAMETROS_TIEMPO_ADICIONAL
FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY := SYS_CONTEXT('APEX$SESSION','APP_USER');
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PARAM_ETAPA_CASE_BU
BEFORE UPDATE ON PARAMETROS_ETAPA_CASE
FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY := SYS_CONTEXT('APEX$SESSION','APP_USER');
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/
