-- Migración 003: tabla PAISES, enriquecimiento de CLIENTES y PROYECTOS,
-- tabla CONTACTOS_CLIENTE, y triggers de auditoría
-- Ejecutar como usuario ESTIMADOR contra FREEPDB1

-- 1. Tabla PAISES (debe crearse antes de FK en CLIENTES)
CREATE TABLE PAISES (
    PAIS_ID     NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(100) NOT NULL,
    CODIGO_ISO  CHAR(2),
    ACTIVO      CHAR(1)       DEFAULT 'S' NOT NULL,
    CONSTRAINT CK_PAISES_ACTIVO CHECK (ACTIVO IN ('S','N')),
    CONSTRAINT UQ_PAISES_NOMBRE UNIQUE (NOMBRE)
);

-- Carga inicial de países
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('Argentina', 'AR');
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('Bolivia',   'BO');
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('Brasil',    'BR');
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('Chile',     'CL');
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('Colombia',  'CO');
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('España',    'ES');
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('México',    'MX');
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('Paraguay',  'PY');
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('Perú',      'PE');
INSERT INTO PAISES (NOMBRE, CODIGO_ISO) VALUES ('Uruguay',   'UY');
COMMIT;

-- 2. Enriquecer CLIENTES
ALTER TABLE CLIENTES ADD (
    DIRECCION  VARCHAR2(400),
    CIUDAD     VARCHAR2(200),
    PAIS_ID    NUMBER         CONSTRAINT FK_CLIENTES_PAIS REFERENCES PAISES(PAIS_ID),
    CREATED_BY VARCHAR2(255),
    CREATED_AT TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_BY VARCHAR2(255),
    UPDATED_AT TIMESTAMP
);

-- 3. Tabla CONTACTOS_CLIENTE
CREATE TABLE CONTACTOS_CLIENTE (
    CONTACTO_ID NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENTE_ID  NUMBER        NOT NULL CONSTRAINT FK_CONTACTOS_CLIENTE REFERENCES CLIENTES(CLIENTE_ID),
    DESCRIPCION VARCHAR2(200) NOT NULL,
    TELEFONO    VARCHAR2(50),
    EMAIL       VARCHAR2(200),
    ORDEN       NUMBER        DEFAULT 10 NOT NULL
);

CREATE INDEX IDX_CONTACTOS_CLIENTE ON CONTACTOS_CLIENTE(CLIENTE_ID);

-- 4. Enriquecer PROYECTOS (columnas nuevas; triggers van abajo)
ALTER TABLE PROYECTOS ADD (
    FECHA_INICIO_ESTIMADA DATE,
    DESCRIPCION           VARCHAR2(4000)
);

-- 5. Triggers para CLIENTES
CREATE OR REPLACE TRIGGER TRG_CLIENTES_BI
BEFORE INSERT ON CLIENTES FOR EACH ROW
BEGIN
    :NEW.CREATED_BY := SYS_CONTEXT('APEX$SESSION','APP_USER');
    :NEW.CREATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLIENTES_BU
BEFORE UPDATE ON CLIENTES FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY := SYS_CONTEXT('APEX$SESSION','APP_USER');
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- 6. Triggers para PROYECTOS (las columnas CREATED_BY/AT ya existen)
CREATE OR REPLACE TRIGGER TRG_PROYECTOS_BI
BEFORE INSERT ON PROYECTOS FOR EACH ROW
BEGIN
    :NEW.CREATED_BY := SYS_CONTEXT('APEX$SESSION','APP_USER');
    :NEW.CREATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PROYECTOS_BU
BEFORE UPDATE ON PROYECTOS FOR EACH ROW
BEGIN
    :NEW.UPDATED_BY := SYS_CONTEXT('APEX$SESSION','APP_USER');
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/
