-- =============================================================================
-- Estimador de Migraciones Forms→APEX — DDL completo del esquema ESTIMADOR
-- Oracle Database 23ai FREE
-- =============================================================================
-- Ejecutar conectado como usuario ESTIMADOR contra FREEPDB1.
-- Las tablas deben crearse en el orden indicado por las dependencias de FK.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- TABLAS BASE (sin dependencias externas)
-- -----------------------------------------------------------------------------

CREATE TABLE paises (
    pais_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR2(100)  NOT NULL,
    codigo_iso CHAR(2),
    activo     CHAR(1)        DEFAULT 'S' NOT NULL,
    CONSTRAINT ck_paises_activo UNIQUE (nombre),
    CONSTRAINT uq_paises_nombre CHECK (activo IN ('S','N'))
);

CREATE TABLE parametros_complejidad (
    parametro_complejidad_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tipo_elemento            VARCHAR2(20)  NOT NULL,
    nivel_complejidad        VARCHAR2(20),
    horas                    NUMBER(6,2)   NOT NULL,
    updated_by               VARCHAR2(255),
    updated_at               TIMESTAMP(6),
    CONSTRAINT ck_param_complejidad_tipo  CHECK (tipo_elemento IN ('FORMULARIO','REPORTE','PLSQL','MENU')),
    CONSTRAINT ck_param_complejidad_nivel CHECK (nivel_complejidad IN ('SIMPLE','SEMI_COMPLEJO','COMPLEJO','MUY_COMPLEJO','MUY_COMPLEJO_PLUS') OR nivel_complejidad IS NULL),
    CONSTRAINT ck_param_complejidad_menu  CHECK ((tipo_elemento = 'MENU' AND nivel_complejidad IS NULL) OR (tipo_elemento <> 'MENU' AND nivel_complejidad IS NOT NULL)),
    CONSTRAINT ck_param_complejidad_horas CHECK (horas > 0),
    CONSTRAINT uq_param_complejidad       UNIQUE (tipo_elemento, nivel_complejidad)
);

CREATE TABLE parametros_etapa_case (
    parametro_etapa_case_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    etapa                   VARCHAR2(20)  NOT NULL,
    orden                   NUMBER(2,0)   NOT NULL,
    peso_porcentaje         NUMBER(5,2)   NOT NULL,
    recursos_paralelos      NUMBER(4,2)   NOT NULL,
    updated_by              VARCHAR2(255),
    updated_at              TIMESTAMP(6),
    CONSTRAINT ck_param_etapa_case_etapa CHECK (etapa IN ('ESTRATEGIA','ANALISIS','DISENO','CONSTRUCCION','TRANSICION')),
    CONSTRAINT ck_param_etapa_case_peso  CHECK (peso_porcentaje >= 0),
    CONSTRAINT ck_param_etapa_case_recur CHECK (recursos_paralelos > 0),
    CONSTRAINT uq_param_etapa_case_etapa UNIQUE (etapa),
    CONSTRAINT uq_param_etapa_case_orden UNIQUE (orden)
);

CREATE TABLE parametros_tiempo_adicional (
    parametro_tiempo_adicional_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    concepto                      VARCHAR2(40)  NOT NULL,
    base_calculo                  VARCHAR2(30)  NOT NULL,
    porcentaje                    NUMBER(5,2)   NOT NULL,
    orden                         NUMBER(2,0)   NOT NULL,
    updated_by                    VARCHAR2(255),
    updated_at                    TIMESTAMP(6),
    CONSTRAINT ck_param_tiempo_adic_conc CHECK (concepto IN ('PRUEBA_FUNCIONAL','ADMINISTRACION','CONTROL_CALIDAD','DBA','DOCUMENTACION')),
    CONSTRAINT ck_param_tiempo_adic_base CHECK (base_calculo IN ('PROGRAMACION','SUBTOTAL_CONSTRUCCION')),
    CONSTRAINT ck_param_tiempo_adic_pct  CHECK (porcentaje >= 0),
    CONSTRAINT uq_param_tiempo_adic_concepto UNIQUE (concepto),
    CONSTRAINT uq_param_tiempo_adic_orden    UNIQUE (orden)
);


-- -----------------------------------------------------------------------------
-- CLIENTES y CONTACTOS
-- -----------------------------------------------------------------------------

CREATE TABLE clientes (
    cliente_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR2(200) NOT NULL,
    direccion  VARCHAR2(400),
    ciudad     VARCHAR2(200),
    pais_id    NUMBER,
    created_by VARCHAR2(255),
    created_at TIMESTAMP(6)  DEFAULT SYSTIMESTAMP,
    updated_by VARCHAR2(255),
    updated_at TIMESTAMP(6),
    CONSTRAINT uq_clientes_nombre UNIQUE (nombre),
    CONSTRAINT fk_clientes_pais   FOREIGN KEY (pais_id) REFERENCES paises (pais_id)
);

CREATE TABLE contactos_cliente (
    contacto_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cliente_id  NUMBER        NOT NULL,
    descripcion VARCHAR2(200) NOT NULL,
    telefono    VARCHAR2(50),
    email       VARCHAR2(200),
    orden       NUMBER        DEFAULT 10 NOT NULL,
    CONSTRAINT fk_contactos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (cliente_id)
);

CREATE INDEX idx_contactos_cliente ON contactos_cliente (cliente_id);


-- -----------------------------------------------------------------------------
-- PROYECTOS y VERSIONES DE ESTIMACIÓN
-- -----------------------------------------------------------------------------

CREATE TABLE proyectos (
    proyecto_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cliente_id            NUMBER        NOT NULL,
    nombre                VARCHAR2(200) NOT NULL,
    descripcion           VARCHAR2(4000),
    fecha_inicio_estimada DATE,
    created_by            VARCHAR2(255) NOT NULL,
    created_at            TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by            VARCHAR2(255),
    updated_at            TIMESTAMP(6),
    CONSTRAINT uq_proyectos_cliente_nombre UNIQUE (cliente_id, nombre),
    CONSTRAINT fk_proyectos_cliente        FOREIGN KEY (cliente_id) REFERENCES clientes (cliente_id)
);

CREATE INDEX ix_proyectos_cliente ON proyectos (cliente_id);

CREATE TABLE versiones_estimacion (
    version_estimacion_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    proyecto_id           NUMBER     NOT NULL,
    numero_version        NUMBER(4,0) NOT NULL,
    created_by            VARCHAR2(255) NOT NULL,
    created_at            TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by            VARCHAR2(255),
    updated_at            TIMESTAMP(6),
    CONSTRAINT ck_versiones_est_numero  CHECK (numero_version > 0),
    CONSTRAINT uq_versiones_est_numero  UNIQUE (proyecto_id, numero_version),
    CONSTRAINT fk_versiones_est_proyecto FOREIGN KEY (proyecto_id) REFERENCES proyectos (proyecto_id)
);

CREATE INDEX ix_versiones_est_proyecto ON versiones_estimacion (proyecto_id);


-- -----------------------------------------------------------------------------
-- SNAPSHOT DE PARÁMETROS POR VERSIÓN DE ESTIMACIÓN
-- (copiados de las tablas globales al crear una versión; quedan congelados)
-- -----------------------------------------------------------------------------

CREATE TABLE estimacion_parametros_complejidad (
    estimacion_param_complejidad_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    version_estimacion_id           NUMBER      NOT NULL,
    tipo_elemento                   VARCHAR2(20) NOT NULL,
    nivel_complejidad               VARCHAR2(20),
    horas                           NUMBER(6,2)  NOT NULL,
    CONSTRAINT ck_est_param_complejidad_tipo  CHECK (tipo_elemento IN ('FORMULARIO','REPORTE','PLSQL','MENU')),
    CONSTRAINT ck_est_param_complejidad_nivel CHECK (nivel_complejidad IN ('SIMPLE','SEMI_COMPLEJO','COMPLEJO','MUY_COMPLEJO','MUY_COMPLEJO_PLUS') OR nivel_complejidad IS NULL),
    CONSTRAINT ck_est_param_complejidad_menu  CHECK ((tipo_elemento = 'MENU' AND nivel_complejidad IS NULL) OR (tipo_elemento <> 'MENU' AND nivel_complejidad IS NOT NULL)),
    CONSTRAINT ck_est_param_complejidad_horas CHECK (horas > 0),
    CONSTRAINT uq_est_param_complejidad       UNIQUE (version_estimacion_id, tipo_elemento, nivel_complejidad),
    CONSTRAINT uq_est_param_complejidad_id    UNIQUE (version_estimacion_id, estimacion_param_complejidad_id),
    CONSTRAINT fk_est_param_complejidad_ver   FOREIGN KEY (version_estimacion_id) REFERENCES versiones_estimacion (version_estimacion_id)
);

CREATE INDEX ix_est_param_complejidad_ver ON estimacion_parametros_complejidad (version_estimacion_id);

CREATE TABLE estimacion_parametros_etapa_case (
    estimacion_param_etapa_case_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    version_estimacion_id          NUMBER      NOT NULL,
    etapa                          VARCHAR2(20) NOT NULL,
    orden                          NUMBER(2,0)  NOT NULL,
    peso_porcentaje                NUMBER(5,2)  NOT NULL,
    recursos_paralelos             NUMBER(4,2)  NOT NULL,
    CONSTRAINT ck_est_param_etapa_case_etapa CHECK (etapa IN ('ESTRATEGIA','ANALISIS','DISENO','CONSTRUCCION','TRANSICION')),
    CONSTRAINT ck_est_param_etapa_case_peso  CHECK (peso_porcentaje >= 0),
    CONSTRAINT ck_est_param_etapa_case_recur CHECK (recursos_paralelos > 0),
    CONSTRAINT uq_est_param_etapa_case       UNIQUE (version_estimacion_id, etapa),
    CONSTRAINT fk_est_param_etapa_case_ver   FOREIGN KEY (version_estimacion_id) REFERENCES versiones_estimacion (version_estimacion_id)
);

CREATE INDEX ix_est_param_etapa_case_ver ON estimacion_parametros_etapa_case (version_estimacion_id);

CREATE TABLE estimacion_parametros_tiempo_adicional (
    estimacion_param_tiempo_adic_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    version_estimacion_id           NUMBER      NOT NULL,
    concepto                        VARCHAR2(40) NOT NULL,
    base_calculo                    VARCHAR2(30) NOT NULL,
    porcentaje                      NUMBER(5,2)  NOT NULL,
    orden                           NUMBER(2,0)  NOT NULL,
    CONSTRAINT ck_est_param_tiempo_adic_conc CHECK (concepto IN ('PRUEBA_FUNCIONAL','ADMINISTRACION','CONTROL_CALIDAD','DBA','DOCUMENTACION')),
    CONSTRAINT ck_est_param_tiempo_adic_base CHECK (base_calculo IN ('PROGRAMACION','SUBTOTAL_CONSTRUCCION')),
    CONSTRAINT ck_est_param_tiempo_adic_pct  CHECK (porcentaje >= 0),
    CONSTRAINT uq_est_param_tiempo_adic      UNIQUE (version_estimacion_id, concepto),
    CONSTRAINT fk_est_param_tiempo_adic_ver  FOREIGN KEY (version_estimacion_id) REFERENCES versiones_estimacion (version_estimacion_id)
);

CREATE INDEX ix_est_param_tiempo_adic_ver ON estimacion_parametros_tiempo_adicional (version_estimacion_id);


-- -----------------------------------------------------------------------------
-- ELEMENTOS Y LÍNEAS DE DETALLE
-- -----------------------------------------------------------------------------

CREATE TABLE elementos (
    elemento_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    version_estimacion_id NUMBER        NOT NULL,
    nombre                VARCHAR2(200) NOT NULL,
    CONSTRAINT uq_elementos_version_id     UNIQUE (version_estimacion_id, elemento_id),
    CONSTRAINT uq_elementos_version_nombre UNIQUE (version_estimacion_id, nombre),
    CONSTRAINT fk_elementos_version        FOREIGN KEY (version_estimacion_id) REFERENCES versiones_estimacion (version_estimacion_id)
);

CREATE INDEX ix_elementos_version ON elementos (version_estimacion_id);

CREATE TABLE lineas_detalle (
    linea_detalle_id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    elemento_id                     NUMBER    NOT NULL,
    version_estimacion_id           NUMBER    NOT NULL,
    estimacion_param_complejidad_id NUMBER    NOT NULL,
    cantidad                        NUMBER(6,0) DEFAULT 1 NOT NULL,
    CONSTRAINT ck_lindet_cantidad           CHECK (cantidad > 0),
    CONSTRAINT fk_lindet_elemento           FOREIGN KEY (version_estimacion_id, elemento_id)
                                                REFERENCES elementos (version_estimacion_id, elemento_id),
    CONSTRAINT fk_lindet_param_complejidad  FOREIGN KEY (version_estimacion_id, estimacion_param_complejidad_id)
                                                REFERENCES estimacion_parametros_complejidad (version_estimacion_id, estimacion_param_complejidad_id)
);

CREATE INDEX ix_lindet_elemento          ON lineas_detalle (elemento_id);
CREATE INDEX ix_lindet_param_complejidad ON lineas_detalle (estimacion_param_complejidad_id);


-- -----------------------------------------------------------------------------
-- TRIGGERS DE AUDITORÍA
-- -----------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_clientes_bi
BEFORE INSERT ON clientes FOR EACH ROW
BEGIN
    :NEW.created_by := SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    :NEW.created_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_clientes_bu
BEFORE UPDATE ON clientes FOR EACH ROW
BEGIN
    :NEW.updated_by := SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_proyectos_bi
BEFORE INSERT ON proyectos FOR EACH ROW
BEGIN
    :NEW.created_by := SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    :NEW.created_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_proyectos_bu
BEFORE UPDATE ON proyectos FOR EACH ROW
BEGIN
    :NEW.updated_by := SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_versiones_estimacion_bu
BEFORE UPDATE ON versiones_estimacion FOR EACH ROW
BEGIN
    :NEW.updated_by := SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_parametros_complejidad_bu
BEFORE UPDATE ON parametros_complejidad FOR EACH ROW
BEGIN
    :NEW.updated_by := SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_parametros_etapa_case_bu
BEFORE UPDATE ON parametros_etapa_case FOR EACH ROW
BEGIN
    :NEW.updated_by := SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_parametros_tiempo_adicional_bu
BEFORE UPDATE ON parametros_tiempo_adicional FOR EACH ROW
BEGIN
    :NEW.updated_by := SYS_CONTEXT('APEX$SESSION', 'APP_USER');
    :NEW.updated_at := SYSTIMESTAMP;
END;
/


-- -----------------------------------------------------------------------------
-- PACKAGE: PKG_ERROR_HANDLER
-- Manejador de errores registrado en la aplicación APEX (app 100).
-- -----------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE pkg_error_handler AS
    FUNCTION handle_error (p_error IN apex_error.t_error)
        RETURN apex_error.t_error_result;
END pkg_error_handler;
/

CREATE OR REPLACE PACKAGE BODY pkg_error_handler AS

    FUNCTION handle_error (p_error IN apex_error.t_error)
        RETURN apex_error.t_error_result
    IS
        l_result          apex_error.t_error_result;
        l_msg             VARCHAR2(4000);
        l_constraint_name VARCHAR2(255);
    BEGIN
        l_result.message          := p_error.message;
        l_result.additional_info  := p_error.additional_info;
        l_result.display_location := CASE
                                         WHEN p_error.is_internal_error
                                             THEN apex_error.c_on_error_page
                                         ELSE apex_error.c_inline_in_notification
                                     END;
        l_result.page_item_name   := p_error.page_item_name;
        l_result.column_alias     := p_error.column_alias;

        IF p_error.ora_sqlcode IN (-2290, -2292) THEN
            -- Extraer nombre del constraint del mensaje ORA: "(SCHEMA.CONSTRAINT_NAME)"
            l_constraint_name := REGEXP_SUBSTR(p_error.ora_sqlerrm, '\((\w+)\.(\w+)\)', 1, 1, NULL, 2);
            l_msg := CASE l_constraint_name
                -- Parámetros globales
                WHEN 'CK_PARAM_COMPLEJIDAD_HORAS'     THEN 'Las horas deben ser un número mayor a 0'
                WHEN 'CK_PARAM_ETAPA_CASE_PESO'       THEN 'El peso no puede ser negativo'
                WHEN 'CK_PARAM_ETAPA_CASE_RECUR'      THEN 'Los recursos paralelos deben ser un número mayor a 0'
                WHEN 'CK_PARAM_TIEMPO_ADIC_PCT'       THEN 'El porcentaje no puede ser negativo'
                -- Parámetros snapshot por versión
                WHEN 'CK_EST_PARAM_COMPLEJIDAD_HORAS' THEN 'Las horas deben ser un número mayor a 0'
                WHEN 'CK_EST_PARAM_ETAPA_CASE_PESO'   THEN 'El peso no puede ser negativo'
                WHEN 'CK_EST_PARAM_ETAPA_CASE_RECUR'  THEN 'Los recursos paralelos deben ser un número mayor a 0'
                WHEN 'CK_EST_PARAM_TIEMPO_ADIC_PCT'   THEN 'El porcentaje no puede ser negativo'
                -- Otras tablas
                WHEN 'CK_LINDET_CANTIDAD'             THEN 'La cantidad debe ser un número mayor a 0'
                WHEN 'CK_VERSIONES_EST_NUMERO'        THEN 'El número de versión debe ser mayor a 0'
                -- Integridad referencial
                WHEN 'FK_PROYECTOS_CLIENTE'           THEN 'No se puede eliminar el cliente porque tiene proyectos asociados'
                WHEN 'FK_CONTACTOS_CLIENTE'           THEN 'No se puede eliminar el cliente porque tiene contactos registrados. Eliminá los contactos primero.'
                WHEN 'FK_VERSIONES_EST_PROYECTO'      THEN 'No se puede eliminar el proyecto porque tiene versiones de estimación asociadas'
                WHEN 'FK_ELEMENTOS_VERSION'           THEN 'No se puede eliminar la versión porque tiene elementos de migración cargados'
                WHEN 'FK_LINDET_ELEMENTO'             THEN 'No se puede eliminar el elemento porque tiene líneas de detalle asociadas'
                WHEN 'FK_LINDET_PARAM_COMPLEJIDAD'    THEN 'No se puede eliminar este parámetro porque está en uso en estimaciones existentes'
                WHEN 'FK_EST_PARAM_COMPLEJIDAD_VER'   THEN 'No se puede eliminar la versión porque tiene parámetros de complejidad asociados'
                WHEN 'FK_EST_PARAM_ETAPA_CASE_VER'    THEN 'No se puede eliminar la versión porque tiene parámetros de etapa CASE asociados'
                WHEN 'FK_EST_PARAM_TIEMPO_ADIC_VER'   THEN 'No se puede eliminar la versión porque tiene parámetros de tiempo adicional asociados'
                ELSE NULL
            END;

            l_result.additional_info  := p_error.ora_sqlerrm;
            l_result.display_location := apex_error.c_inline_in_notification;

            IF l_msg IS NOT NULL THEN
                l_result.message := l_msg;
            ELSE
                l_result.message := 'Se produjo un error al guardar los datos. Por favor, revisá los valores ingresados e intentá de nuevo.';
            END IF;
        END IF;

        RETURN l_result;
    END handle_error;

END pkg_error_handler;
/


-- -----------------------------------------------------------------------------
-- DATOS DE REFERENCIA INICIALES
-- -----------------------------------------------------------------------------

-- Países (América Latina + España)
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('Argentina', 'AR', 'S');
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('Bolivia',   'BO', 'S');
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('Brasil',    'BR', 'S');
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('Chile',     'CL', 'S');
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('Colombia',  'CO', 'S');
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('España',    'ES', 'S');
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('México',    'MX', 'S');
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('Paraguay',  'PY', 'S');
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('Perú',      'PE', 'S');
INSERT INTO paises (nombre, codigo_iso, activo) VALUES ('Uruguay',   'UY', 'S');

-- Parámetros globales de complejidad (valores vigentes de la planilla Excel)
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('FORMULARIO', 'SIMPLE',           3);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('FORMULARIO', 'SEMI_COMPLEJO',   12);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('FORMULARIO', 'COMPLEJO',        24);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('FORMULARIO', 'MUY_COMPLEJO',    32);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('FORMULARIO', 'MUY_COMPLEJO_PLUS', 80);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('REPORTE',    'SIMPLE',           4);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('REPORTE',    'SEMI_COMPLEJO',    8);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('REPORTE',    'COMPLEJO',        24);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('REPORTE',    'MUY_COMPLEJO',    40);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('REPORTE',    'MUY_COMPLEJO_PLUS', 64);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('PLSQL',      'SIMPLE',           4);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('PLSQL',      'SEMI_COMPLEJO',    8);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('PLSQL',      'COMPLEJO',        24);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('PLSQL',      'MUY_COMPLEJO',    32);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('PLSQL',      'MUY_COMPLEJO_PLUS', 80);
INSERT INTO parametros_complejidad (tipo_elemento, nivel_complejidad, horas) VALUES ('MENU',       NULL,               4);

-- Etapas CASE (distribución de horas y recursos)
INSERT INTO parametros_etapa_case (etapa, orden, peso_porcentaje, recursos_paralelos) VALUES ('ESTRATEGIA',   1,  7, 1);
INSERT INTO parametros_etapa_case (etapa, orden, peso_porcentaje, recursos_paralelos) VALUES ('ANALISIS',     2, 13, 2);
INSERT INTO parametros_etapa_case (etapa, orden, peso_porcentaje, recursos_paralelos) VALUES ('DISENO',       3, 19, 2);
INSERT INTO parametros_etapa_case (etapa, orden, peso_porcentaje, recursos_paralelos) VALUES ('CONSTRUCCION', 4, 38, 2);
INSERT INTO parametros_etapa_case (etapa, orden, peso_porcentaje, recursos_paralelos) VALUES ('TRANSICION',   5, 23, 1);

-- Tiempos adicionales (porcentajes sobre la base de cálculo indicada)
INSERT INTO parametros_tiempo_adicional (concepto, base_calculo, porcentaje, orden) VALUES ('PRUEBA_FUNCIONAL', 'PROGRAMACION',         15, 1);
INSERT INTO parametros_tiempo_adicional (concepto, base_calculo, porcentaje, orden) VALUES ('ADMINISTRACION',   'SUBTOTAL_CONSTRUCCION',  5, 2);
INSERT INTO parametros_tiempo_adicional (concepto, base_calculo, porcentaje, orden) VALUES ('CONTROL_CALIDAD',  'SUBTOTAL_CONSTRUCCION',  1, 3);
INSERT INTO parametros_tiempo_adicional (concepto, base_calculo, porcentaje, orden) VALUES ('DBA',              'SUBTOTAL_CONSTRUCCION',  2, 4);
INSERT INTO parametros_tiempo_adicional (concepto, base_calculo, porcentaje, orden) VALUES ('DOCUMENTACION',    'SUBTOTAL_CONSTRUCCION',  3, 5);

COMMIT;
